package com.game.constants;

public interface MessageConstants {


   String START_GAME_TO_SAVE = "START_GAME_TO_SAVE";
   String SAVE_ERROR = "SAVE_ERROR";
   String LOAD_ERROR = "LOAD_ERROR";
   String NO_SAVES = "NO_SAVES";
   String GAME_ALREADY_WON = "GAME_ALREADY_WON";
   String XP_MESSAGE = "XP_MESSAGE";
   String MAIN_MENU_OPTION = "MAIN_MENU_OPTION";
   String DIFFICULTY_OPTION = "DIFFICULTY_OPTION";
   String CHARACTER_NAME_OPTION = "CHARACTER_NAME_OPTION";
   String PLAYER_CLASS_OPTION = "PLAYER_CLASS_OPTION";
   String CHARACTER_MOVEMENT_OPTION = "CHARACTER_MOVEMENT_OPTION";
   String CHARACTER_FIGHTING_OPTION = "CHARACTER_FIGHTING_OPTION";
   String UNABLE_TO_FIND_PLAYER = "UNABLE_TO_FIND_PLAYER";
   String DEAL_ENEMY_DAMAGE = "DEAL_ENEMY_DAMAGE";
   String ENEMY_HEALTH_STATUS = "ENEMY_HEALTH_STATUS";
   String ENEMY_KILLED = "ENEMY_KILLED";
   String DEAL_PLAYER_DAMAGE = "DEAL_PLAYER_DAMAGE";
   String PLAYER_HEALTH_STATUS = "PLAYER_HEALTH_STATUS";
   String GAME_OVER = "GAME_OVER";
   String SHIELD_UP = "SHIELD_UP";
   String SHIELD_ABSORBS_ALL_DAMAGE = "SHIELD_ABSORBS_ALL_DAMAGE";
   String WIN_MESSAGE = "WIN_MESSAGE";

}
